project 'JJFloatingActionButton.xcodeproj'
platform :ios, '9.0'

target 'JJFloatingActionButton_Example' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'JJFloatingActionButton', :path => '../'

  target 'JJFloatingActionButton_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'

  end

end
