source 'https://github.com/CocoaPods/Specs.git'
project 'JJFloatingActionButton.xcodeproj'

deployment_target = '13.0'
platform :ios, deployment_target

target 'JJFloatingActionButton_Example' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'JJFloatingActionButton', :path => '../'

  target 'JJFloatingActionButton_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'

  end
  
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
    end
  end
end
