included:
  - Sources
  - Example
excluded:
- Example/Pods
- Example/Tests

disabled_rules:
  - redundant_objc_attribute

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - nimble_operator
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - number_separator
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - let_var_whitespace
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation


line_length: 140
file_length: 1000
function_body_length: 40
