language: objective-c
osx_image: xcode9.1
branches:
  only:
    - develop
    - master
    - /^release.*$/
    - /^hotfix.*$/
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE="Example/JJFloatingActionButton.xcworkspace"
    - SCHEME="JJFloatingActionButton_Example"
    - SDK="iphonesimulator11.1"
  matrix:
    - DESTINATION="OS=11.1,name=iPhone X"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"
    - DESTINATION="OS=9.3,name=iPhone 6"
cache:
  - cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install --repo-update --project-directory=Example
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO
  - pod lib lint
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
